#%RAML 1.0
title: AI API Server
description: A collection of AI API services inteded for client apps.
version: v1
baseUri: /api/v1

/qa: !include qa.raml
/qs: !include qs.raml
/iv: !include iv.raml
/h5p: !include h5p.raml
# /ms-bot: !include ms-bot.raml
/server: !include ../node_modules/du-server/raml/du-server.raml