#%RAML 1.0
title: IDR Content server
description: Combined du- module raml specs.
version: v1
baseUri: /api/v1

/server: !include ../node_modules/du-server/raml/du-server.raml
/qg: !include question-generation.raml