#%RAML 1.0
description: Generates H5P quiz generator packages.

/generate-quiz/{resourceId}:
  description: Generate a H5P interactive video content. Returns a zipped H5P package
  uriParameters:
    resourceId:
      type: string
  get:
    queryParameters:
      isTest:
        description: Just return the h5p content.json is response
        type: boolean
        required: false
      isReturnTypeZip:
        description: If True return file with extension .zip otherwise defaults to .h5p
        type: boolean
        required: false
      resourceType:
        description: resourceType = 'quiz' if resourceId is a quizId otherwise resourceId will be assumed to be an ivideo
        type: string
        required: false 
    responses:
      200:
        description: Generate a H5P package.
        body:
          application/zip:
      500:
        description: Unexpected Error or bad parameter



