#%RAML 1.0
#title: Question generation and question answering AI service.

/quiz/{quizId}:
  uriParameters:
    quizId:
      type: string
      description: quiz id 
      displayName: Quiz id
  get:
    responses:
      200:
        description: Retrieve the quiz for the given quiz id
        body:
          application/json:
            example: |
                {
                  "success": true,
                  "result": {}
                }
      500:
        description: Unexpected Error or bad parameters
  delete:
    responses:
      200:
        description: Removes quiz
      500:
        description: Unexpected Error or bad parameter

/quiz:
  put:
    body:
      application/json:
        properties:
          plainText:
            type: string
            required: true    
          richText:
            type: string
            required: false
          tokens:    
            type: string[]
            required: false
    responses:
      200:
        description: Store document quiz for further queries
        body:
          application/json:
            example: |
              {
                "success": true
                "quizId": "5eb390b946cc9f61db34bb3c"
              }
      500:
        description: Unexpected Error or bad parameter


/generate-question/{quizId}:
  description: Generate question from quiz and answer token
  uriParameters:
    quizId:
      type: string
      description: quiz id 
      displayName: Quiz id
  get:
    queryParameters:
      answerToken:
        description: The answer token
        displayName: Answer Token
        type: string
        required: true

/generate-questions/{quizId}:
  description: Generate question from quiz and all answer tokens
  uriParameters:
    quizId:
      type: string
      description: quiz id 
      displayName: Quiz id
  put:

/answer-question/{quizId}:
  description: Answer questions from quiz and question token
  uriParameters:
    quizId:
      type: string
      description: quiz id 
      displayName: Quiz id
  get:
    queryParameters:
      questionToken:
        description: The question token
        displayName: Question Token
        type: string
        required: true
