#%RAML 1.0
description: Question generation and question answering AI service.

/quizzes:
  get:
    description: Get list of quizzes
    responses:
      200:
        description: Retrieve quizzes tokens and status
        body:
          application/json:
            example: |
                {
                  "success": true,
                  "data": {}
                }
      500:
        description: Unexpected Error or bad parameters

/quiz/{quizId}:
  uriParameters:
    quizId:
      type: string
  get:
    responses:
      200:
        description: Retrieve the quiz for the given quiz id
        body:
          application/json:
            example: |
                {
                  success: true,
                  data: {
                    "plainText": "<plain text>",
                    "richText": "<rich text>",
                    "tokens": [{
                      "answerToken": "<answer token>",
                      "questionToken": "<question token>",
                      "status": "pending|processing|processed"
                    }]
                  }
                }
      500:
        description: Unexpected Error or bad parameters
  delete:
    responses:
      200:
        description: Removes quiz
      500:
        description: Unexpected Error or bad parameter

/quiz-tokens/{quizId}:
  uriParameters:
    quizId:
      type: string
  get:
    description: Get the tokens part of the quiz so that progress of quiz generation can be checked.
    responses:
      200:
        description: Retrieve the quiz tokens and status for the given quiz id
        body:
          application/json:
            example: |
                {
                  "success": true,
                  "data": {}
                }
      500:
        description: Unexpected Error or bad parameters

/quiz:
  put:
    body:
      application/json:
        properties:
          _id:
            type: string
            required: false 
          name:
            type: string
            required: true
            description: The title / name of the quiz    
          plainText:
            type: string
            required: true    
          richText:
            type: string
            required: false
          answerTokens:    
            type: string[]
            required: false
    responses:
      200:
        description: Store document quiz for further queries
        body:
          application/json:
            example: |
              {
                "success": true
                "data": "<quiz id>"
              }
      500:
        description: Unexpected Error or bad parameter


/generate-question/{quizId}:
  description: Generate question from quiz and answer token
  uriParameters:
    quizId:
      type: string
  get:
    queryParameters:
      answerToken:
        description: The answer token
        type: string
        required: true

/generate-questions/{quizId}:
  description: Generate question from quiz and all answer tokens
  uriParameters:
    quizId:
      type: string
  put:
    responses:
      200:
        description: Processes all tokens on quiz to generate a questions
        body:
          application/json:
            example: |
              {
                "success": true
                "data": "<quiz id>"
              }
      500:
        description: Unexpected Error or bad parameter

/answer-question/{quizId}:
  description: Answer questions from quiz and question token
  uriParameters:
    quizId:
      type: string
  get:
    queryParameters:
      questionToken:
        description: The question token
        type: string
        required: true
