build_image_ai_api:
  stage: build
  only:
    - master
  tags:
    - docker
  services:
    - name: docker-hub.artifactory.its.deakin.edu.au/docker:18.09-dind
      alias: docker
  script:
    - cd ai-api-server/
    - echo $DOCKER_AUTH > ~/password.txt
    - cat ~/password.txt | docker login --username bamboo --password-stdin $REPO
    - docker build -t $REPO/ai-api-server:$CI_COMMIT_SHA --rm -f Dockerfile .
    - docker push $REPO/ai-api-server:$CI_COMMIT_SHA

deploy_stage_ai_api:
  stage: deploy
  only:
    - master
  tags:
    - docker
  variables:
    ENV_TAG: $CI_COMMIT_SHA
    DOCKER_HOST: "tcp://apps-docker-f1.its.deakin.edu.au:2375"
  services:
    - name: docker-hub.artifactory.its.deakin.edu.au/docker:18.09-dind
      alias: docker
  script:
    - cd ai-api-server/
    - echo $DOCKER_AUTH > ~/password.txt
    - cat ~/password.txt | docker login --username bamboo --password-stdin $REPO
    - docker stack deploy -c docker-compose.yml des-inno-ai-api
