version: "3.7"

services:
  #note: images are for gitlab.
  ai-api-server:
    container_name: ai-api-server
    image: local-des-inno-docker.artifactory.its.deakin.edu.au/ai-api-server:${ENV_TAG}
    restart: unless-stopped
    #build: .
    # ports:
    #   - "7040:7040"
    networks:
      - ai-api-mongo
      - traefik-int
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-int"
        - "traefik.http.routers.ai-api.rule=Host(`des-inno-ai-api.its.deakin.edu.au`)"
        - "traefik.http.routers.ai-api.entrypoints=web"
        - "traefik.http.routers.ai-api.service=ai-api"
        - "traefik.http.services.ai-api.loadbalancer.server.port=7040"  
  ai-api-mongo:
    container_name: ai-api-mongo
    image: docker-hub.artifactory.its.deakin.edu.au/mongo
    networks:
      - ai-api-mongo
    volumes:
      - mongo-data:/data/db
    deploy:
      mode: replicated
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        constraints: [node.labels.supermaster == true]
      
networks:
  ai-api-mongo:
  traefik-int:
    external: true
volumes:
  mongo-data:




