version: '3.7'
services:
    ai-qg-app:
      container_name: ai-qg-app
      image: local-des-inno-docker.artifactory.its.deakin.edu.au/ai-qg-app:${ENV_TAG} 
      restart: unless-stopped
      networks:
        - traefik-int
      deploy:
        mode: replicated
        replicas: 1
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik-int"
            - "traefik.http.routers.ai-qg-app.rule=Host(`des-inno-ai-qg-app.its.deakin.edu.au`)"
            - "traefik.http.routers.ai-qg-app.entrypoints=web"
            - "traefik.http.routers.ai-qg-app.service=ai-qg-app"
            - "traefik.http.services.ai-qg-app.loadbalancer.server.port=80"

networks:
  traefik-int:
    external: true
  